// local a = b, c -> {return b + c}

// local z = console.log

// z(a(1, 2))
// // console.log(a(1, 2))


// local t = {a: 2, b: 3}
// t -> a {console.log(a)}


// async {
//     console.log('amogus')
// }
// async {
//     i = 3 -> 1000 {
//         console.log(i)
//     }
// }


local a = b, c -> {return b + c}


1, 2 -> a -> local z

// TODO: FIX
// a() -> local z

// a() -> (t) -> {console.log(t) return t} -> local z

console.log(z)